'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsLeerPerformance
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsLeerPerformanceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsLeerPerformance
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AutorizadasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_5OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_35OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_6OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_65OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_66OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_67OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_70OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_71OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_72OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_73OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_74OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_8OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_87OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_VariosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PuertoDisponibleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Codigo_11OperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnvioCorreoEspecialOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MonitoreoLOGS.My.MySettings.Default.MonitoreoLOGS_wsLeerPerformance_wsLeerPerformance
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AutorizadasCompleted As AutorizadasCompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_2Completed As Codigo_2CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_5Completed As Codigo_5CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_35Completed As Codigo_35CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_6Completed As Codigo_6CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_65Completed As Codigo_65CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_66Completed As Codigo_66CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_67Completed As Codigo_67CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_70Completed As Codigo_70CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_71Completed As Codigo_71CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_72Completed As Codigo_72CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_73Completed As Codigo_73CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_74Completed As Codigo_74CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_8Completed As Codigo_8CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_87Completed As Codigo_87CompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_VariosCompleted As Codigo_VariosCompletedEventHandler
        
        '''<remarks/>
        Public Event PuertoDisponibleCompleted As PuertoDisponibleCompletedEventHandler
        
        '''<remarks/>
        Public Event Codigo_11Completed As Codigo_11CompletedEventHandler
        
        '''<remarks/>
        Public Event EnvioCorreoEspecialCompleted As EnvioCorreoEspecialCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Autorizadas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Autorizadas() As MonitoreoData
            Dim results() As Object = Me.Invoke("Autorizadas", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizadasAsync()
            Me.AutorizadasAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizadasAsync(ByVal userState As Object)
            If (Me.AutorizadasOperationCompleted Is Nothing) Then
                Me.AutorizadasOperationCompleted = AddressOf Me.OnAutorizadasOperationCompleted
            End If
            Me.InvokeAsync("Autorizadas", New Object(-1) {}, Me.AutorizadasOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizadasOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizadasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizadasCompleted(Me, New AutorizadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_2() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_2", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_2Async()
            Me.Codigo_2Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_2Async(ByVal userState As Object)
            If (Me.Codigo_2OperationCompleted Is Nothing) Then
                Me.Codigo_2OperationCompleted = AddressOf Me.OnCodigo_2OperationCompleted
            End If
            Me.InvokeAsync("Codigo_2", New Object(-1) {}, Me.Codigo_2OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_2OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_2Completed(Me, New Codigo_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_5", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_5() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_5", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_5Async()
            Me.Codigo_5Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_5Async(ByVal userState As Object)
            If (Me.Codigo_5OperationCompleted Is Nothing) Then
                Me.Codigo_5OperationCompleted = AddressOf Me.OnCodigo_5OperationCompleted
            End If
            Me.InvokeAsync("Codigo_5", New Object(-1) {}, Me.Codigo_5OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_5OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_5CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_5Completed(Me, New Codigo_5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_35", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_35() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_35", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_35Async()
            Me.Codigo_35Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_35Async(ByVal userState As Object)
            If (Me.Codigo_35OperationCompleted Is Nothing) Then
                Me.Codigo_35OperationCompleted = AddressOf Me.OnCodigo_35OperationCompleted
            End If
            Me.InvokeAsync("Codigo_35", New Object(-1) {}, Me.Codigo_35OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_35OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_35CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_35Completed(Me, New Codigo_35CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_6", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_6() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_6", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_6Async()
            Me.Codigo_6Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_6Async(ByVal userState As Object)
            If (Me.Codigo_6OperationCompleted Is Nothing) Then
                Me.Codigo_6OperationCompleted = AddressOf Me.OnCodigo_6OperationCompleted
            End If
            Me.InvokeAsync("Codigo_6", New Object(-1) {}, Me.Codigo_6OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_6OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_6CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_6Completed(Me, New Codigo_6CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_65", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_65() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_65", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_65Async()
            Me.Codigo_65Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_65Async(ByVal userState As Object)
            If (Me.Codigo_65OperationCompleted Is Nothing) Then
                Me.Codigo_65OperationCompleted = AddressOf Me.OnCodigo_65OperationCompleted
            End If
            Me.InvokeAsync("Codigo_65", New Object(-1) {}, Me.Codigo_65OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_65OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_65CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_65Completed(Me, New Codigo_65CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_66", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_66() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_66", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_66Async()
            Me.Codigo_66Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_66Async(ByVal userState As Object)
            If (Me.Codigo_66OperationCompleted Is Nothing) Then
                Me.Codigo_66OperationCompleted = AddressOf Me.OnCodigo_66OperationCompleted
            End If
            Me.InvokeAsync("Codigo_66", New Object(-1) {}, Me.Codigo_66OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_66OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_66CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_66Completed(Me, New Codigo_66CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_67", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_67() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_67", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_67Async()
            Me.Codigo_67Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_67Async(ByVal userState As Object)
            If (Me.Codigo_67OperationCompleted Is Nothing) Then
                Me.Codigo_67OperationCompleted = AddressOf Me.OnCodigo_67OperationCompleted
            End If
            Me.InvokeAsync("Codigo_67", New Object(-1) {}, Me.Codigo_67OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_67OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_67CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_67Completed(Me, New Codigo_67CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_70", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_70() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_70", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_70Async()
            Me.Codigo_70Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_70Async(ByVal userState As Object)
            If (Me.Codigo_70OperationCompleted Is Nothing) Then
                Me.Codigo_70OperationCompleted = AddressOf Me.OnCodigo_70OperationCompleted
            End If
            Me.InvokeAsync("Codigo_70", New Object(-1) {}, Me.Codigo_70OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_70OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_70CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_70Completed(Me, New Codigo_70CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_71", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_71() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_71", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_71Async()
            Me.Codigo_71Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_71Async(ByVal userState As Object)
            If (Me.Codigo_71OperationCompleted Is Nothing) Then
                Me.Codigo_71OperationCompleted = AddressOf Me.OnCodigo_71OperationCompleted
            End If
            Me.InvokeAsync("Codigo_71", New Object(-1) {}, Me.Codigo_71OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_71OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_71CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_71Completed(Me, New Codigo_71CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_72", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_72() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_72", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_72Async()
            Me.Codigo_72Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_72Async(ByVal userState As Object)
            If (Me.Codigo_72OperationCompleted Is Nothing) Then
                Me.Codigo_72OperationCompleted = AddressOf Me.OnCodigo_72OperationCompleted
            End If
            Me.InvokeAsync("Codigo_72", New Object(-1) {}, Me.Codigo_72OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_72OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_72CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_72Completed(Me, New Codigo_72CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_73", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_73() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_73", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_73Async()
            Me.Codigo_73Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_73Async(ByVal userState As Object)
            If (Me.Codigo_73OperationCompleted Is Nothing) Then
                Me.Codigo_73OperationCompleted = AddressOf Me.OnCodigo_73OperationCompleted
            End If
            Me.InvokeAsync("Codigo_73", New Object(-1) {}, Me.Codigo_73OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_73OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_73CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_73Completed(Me, New Codigo_73CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_74", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_74() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_74", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_74Async()
            Me.Codigo_74Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_74Async(ByVal userState As Object)
            If (Me.Codigo_74OperationCompleted Is Nothing) Then
                Me.Codigo_74OperationCompleted = AddressOf Me.OnCodigo_74OperationCompleted
            End If
            Me.InvokeAsync("Codigo_74", New Object(-1) {}, Me.Codigo_74OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_74OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_74CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_74Completed(Me, New Codigo_74CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_8", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_8() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_8", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_8Async()
            Me.Codigo_8Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_8Async(ByVal userState As Object)
            If (Me.Codigo_8OperationCompleted Is Nothing) Then
                Me.Codigo_8OperationCompleted = AddressOf Me.OnCodigo_8OperationCompleted
            End If
            Me.InvokeAsync("Codigo_8", New Object(-1) {}, Me.Codigo_8OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_8OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_8CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_8Completed(Me, New Codigo_8CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_87", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_87() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_87", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_87Async()
            Me.Codigo_87Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_87Async(ByVal userState As Object)
            If (Me.Codigo_87OperationCompleted Is Nothing) Then
                Me.Codigo_87OperationCompleted = AddressOf Me.OnCodigo_87OperationCompleted
            End If
            Me.InvokeAsync("Codigo_87", New Object(-1) {}, Me.Codigo_87OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_87OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_87CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_87Completed(Me, New Codigo_87CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_Varios", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_Varios() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_Varios", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_VariosAsync()
            Me.Codigo_VariosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_VariosAsync(ByVal userState As Object)
            If (Me.Codigo_VariosOperationCompleted Is Nothing) Then
                Me.Codigo_VariosOperationCompleted = AddressOf Me.OnCodigo_VariosOperationCompleted
            End If
            Me.InvokeAsync("Codigo_Varios", New Object(-1) {}, Me.Codigo_VariosOperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_VariosOperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_VariosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_VariosCompleted(Me, New Codigo_VariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PuertoDisponible", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PuertoDisponible(ByVal sPTO As String) As String
            Dim results() As Object = Me.Invoke("PuertoDisponible", New Object() {sPTO})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PuertoDisponibleAsync(ByVal sPTO As String)
            Me.PuertoDisponibleAsync(sPTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PuertoDisponibleAsync(ByVal sPTO As String, ByVal userState As Object)
            If (Me.PuertoDisponibleOperationCompleted Is Nothing) Then
                Me.PuertoDisponibleOperationCompleted = AddressOf Me.OnPuertoDisponibleOperationCompleted
            End If
            Me.InvokeAsync("PuertoDisponible", New Object() {sPTO}, Me.PuertoDisponibleOperationCompleted, userState)
        End Sub
        
        Private Sub OnPuertoDisponibleOperationCompleted(ByVal arg As Object)
            If (Not (Me.PuertoDisponibleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PuertoDisponibleCompleted(Me, New PuertoDisponibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Codigo_11", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codigo_11() As MonitoreoData
            Dim results() As Object = Me.Invoke("Codigo_11", New Object(-1) {})
            Return CType(results(0),MonitoreoData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Codigo_11Async()
            Me.Codigo_11Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Codigo_11Async(ByVal userState As Object)
            If (Me.Codigo_11OperationCompleted Is Nothing) Then
                Me.Codigo_11OperationCompleted = AddressOf Me.OnCodigo_11OperationCompleted
            End If
            Me.InvokeAsync("Codigo_11", New Object(-1) {}, Me.Codigo_11OperationCompleted, userState)
        End Sub
        
        Private Sub OnCodigo_11OperationCompleted(ByVal arg As Object)
            If (Not (Me.Codigo_11CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Codigo_11Completed(Me, New Codigo_11CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioCorreoEspecial", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnvioCorreoEspecial(ByVal configuracionMail As configuracionMail, ByVal titulo As String, ByVal mensaje As String, ByVal esError As Boolean) As RespuestaCorreo
            Dim results() As Object = Me.Invoke("EnvioCorreoEspecial", New Object() {configuracionMail, titulo, mensaje, esError})
            Return CType(results(0),RespuestaCorreo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoEspecialAsync(ByVal configuracionMail As configuracionMail, ByVal titulo As String, ByVal mensaje As String, ByVal esError As Boolean)
            Me.EnvioCorreoEspecialAsync(configuracionMail, titulo, mensaje, esError, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoEspecialAsync(ByVal configuracionMail As configuracionMail, ByVal titulo As String, ByVal mensaje As String, ByVal esError As Boolean, ByVal userState As Object)
            If (Me.EnvioCorreoEspecialOperationCompleted Is Nothing) Then
                Me.EnvioCorreoEspecialOperationCompleted = AddressOf Me.OnEnvioCorreoEspecialOperationCompleted
            End If
            Me.InvokeAsync("EnvioCorreoEspecial", New Object() {configuracionMail, titulo, mensaje, esError}, Me.EnvioCorreoEspecialOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnvioCorreoEspecialOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnvioCorreoEspecialCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnvioCorreoEspecialCompleted(Me, New EnvioCorreoEspecialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MonitoreoData
        
        Private contadorField As Integer
        
        Private nombreServidorField As String
        
        '''<remarks/>
        Public Property contador() As Integer
            Get
                Return Me.contadorField
            End Get
            Set
                Me.contadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nombreServidor() As String
            Get
                Return Me.nombreServidorField
            End Get
            Set
                Me.nombreServidorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaCorreo
        
        Private esExitosoField As Boolean
        
        Private descripcionErrorField As String
        
        '''<remarks/>
        Public Property esExitoso() As Boolean
            Get
                Return Me.esExitosoField
            End Get
            Set
                Me.esExitosoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescripcionError() As String
            Get
                Return Me.descripcionErrorField
            End Get
            Set
                Me.descripcionErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class configuracionMail
        
        Private usuarioField As String
        
        Private smtpField As String
        
        Private passField As String
        
        Private conCertificadoField As Boolean
        
        Private puertoField As Integer
        
        Private listaDestinatariosField() As String
        
        Private listaDestinatariosErrorField() As String
        
        Private remitenteField As String
        
        Private pathLogoField As String
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property smtp() As String
            Get
                Return Me.smtpField
            End Get
            Set
                Me.smtpField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pass() As String
            Get
                Return Me.passField
            End Get
            Set
                Me.passField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property conCertificado() As Boolean
            Get
                Return Me.conCertificadoField
            End Get
            Set
                Me.conCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property puerto() As Integer
            Get
                Return Me.puertoField
            End Get
            Set
                Me.puertoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property listaDestinatarios() As String()
            Get
                Return Me.listaDestinatariosField
            End Get
            Set
                Me.listaDestinatariosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property listaDestinatariosError() As String()
            Get
                Return Me.listaDestinatariosErrorField
            End Get
            Set
                Me.listaDestinatariosErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property remitente() As String
            Get
                Return Me.remitenteField
            End Get
            Set
                Me.remitenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pathLogo() As String
            Get
                Return Me.pathLogoField
            End Get
            Set
                Me.pathLogoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub AutorizadasCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizadasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizadasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_2CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_5CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_5CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_5CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_35CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_35CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_35CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_6CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_6CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_6CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_65CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_65CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_65CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_66CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_66CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_66CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_67CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_67CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_67CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_70CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_70CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_70CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_71CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_71CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_71CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_72CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_72CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_72CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_73CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_73CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_73CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_74CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_74CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_74CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_8CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_8CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_8CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_87CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_87CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_87CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_VariosCompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_VariosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_VariosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub PuertoDisponibleCompletedEventHandler(ByVal sender As Object, ByVal e As PuertoDisponibleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PuertoDisponibleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Codigo_11CompletedEventHandler(ByVal sender As Object, ByVal e As Codigo_11CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Codigo_11CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MonitoreoData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MonitoreoData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub EnvioCorreoEspecialCompletedEventHandler(ByVal sender As Object, ByVal e As EnvioCorreoEspecialCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnvioCorreoEspecialCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCorreo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCorreo)
            End Get
        End Property
    End Class
End Namespace
